### PR TITLE
Roughed out deliverable 3 v1

### PR DESCRIPTION
**Pull request by 7thStringofZhef**
Roughed out some stuff for deliverable 3. Have working unit tests (some of which fail, but haven't figured it out yet), links to persistent PostgreSQL objects, pbdfk2+SHA256 hashing of user passwords. Will probably add some job functionality as well before class, but wanted a workable model up now in case.

### CODE REVIEW

**Comment by AdityaMahadevan** [comment]
Just looked over what you added and noticed one thing. The schema you have doesn't match up with what they have here (specifically the types): https://github.com/OSGConnect/freesurfer_workflow/blob/master/postgresql/schema.sql

**Comment by 7thStringofZhef** [comment]
I realize it doesn't match their types, but the hSQL setup I'm using doesn't match the syntax that they use, and I figured it would be better to have a nearly-correct database than none at all. It still works, it just requires programmer enforcement of job states for now. I'm gonna talk to Troy about the way the database he implemented works so I can see about converting to it after this deliverable.

**Comment by 7thStringofZhef** [comment]
Also, I made another chunk of changes to add job functionality

**Comment by AdityaMahadevan** [comment]
Alright, just wanted to make sure you were aware. I'll go ahead and merge this.

**Pull request merged**
